import { ElementRef, EventEmitter } from '@angular/core';
import { ExtDate, ExtInterval } from 'extdate';
export declare class InfiniteCalendarComponent {
    scrollView: ElementRef;
    height: number;
    position: string;
    navForToday: boolean;
    navForPrevMonth: boolean;
    navForPrevYear: boolean;
    navForNextMonth: boolean;
    navForNextYear: boolean;
    labelForToday: string;
    selectDate: EventEmitter<ExtDate>;
    selectInterval: EventEmitter<ExtInterval>;
    maxRowsInVirtualContainer: number;
    maxRowsOnWindow: number;
    scrollDuration: number;
    hovering: [number, number];
    selecting: [number, number];
    vAddr: any;
    pAddr: any[][];
    loadable: boolean;
    origin: ExtDate;
    currentDate: ExtDate;
    beginningOnWindow: ExtDate;
    endOnWindow: ExtDate;
    constructor();
    ngOnInit(): void;
    ngAfterViewInit(): void;
    onClickBackToToday(): void;
    onClickDate(event: any, addr: any): void;
    onMouseoverDate(event: any, addr: any): void;
    onScroll(event: any): void;
    private _appendMonthToTop();
    private _appendMonthToBottom();
    private _calcVirtualAddress(date);
    private _scrollTo(element, offsetTop, duration);
    private _easing(pattern);
}
